# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-17 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
